kind: Service
apiVersion: v1
metadata: 
  name: nginx-app-service
  namespace: nginx
  labels:
    env: dev
spec:
  selector:
    app: notes-app-k8s
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

   
