apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  namespace: mysql
spec:
  selector: 
    app: mysql
  ports: 
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

