kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: webapp-deamonset
  namespace: nginx
  labels:
    tier: frontend-deamonset
    env: Dev
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80


