kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment
  labels:
    tier: frontend
    env: Dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80


