kind: Job
apiVersion: batch/v1
metadata: 
  name: demo-job
  labels: 
    app: webapp
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: webapp
      labels: 
        app: job-demo
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["sh","-c","echo hello world && sleep 10"]
      restartPolicy: Never
