apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: front-end
spec:
  containers:
  - name: webapp
    image: nginx
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "app"
            operator: In
            values:
            - "front-end"
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "team"
            operator: In
            values:
            - "Devops"


