kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["","apps"]
    resources: ["pods","deployments","services"]
    verbs: ["get"]


