apiVersion: v1
kind: Namespace
metadata: 
  name: apache

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
  namespace: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata: 
      labels:
        app: apache 
    spec:
      containers:
        - name: appache-cont
          image: httpd:latest
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
