apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["*"]
    resources: ["pod","deployment","service"]
    verbs: ["apply","get","watch","create","list"]
