kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: claim-volume
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage


