kind: PersistentVolume
apiVersion: v1
metadata: 
  name: local-ng-pv
  namespace: nginx
  labels: 
    app: db
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
