kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-pod
  namespace: nginx
  labels:
    app: front-end
    env: UAT
spec:
  repicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    matadata:
      name: nginx-deployment pod 
      labels:
        app: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
