kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: nginx
  labels:
    app: front-end
    env: UAT
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80


