apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
  namespace: apache
  labels:
    app: apache
spec:
  containers:
    - name: stress-container
      image: busybox
      command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://apache-service.apache.svc.cluster.local; done"
      resources:
        requests:
          cpu: 300m
        limits:
          cpu: 500m

